### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by bardo84** [GunnarFarneback/DynamicallyLoadedEmbedding.jl#4]
Hi, running v1.7.2 on Windows 10 and MSYS2 toolchain, I get

PS C:\Users\xxx> cd C:\Users\xxx\.julia\packages\DynamicallyLoadedEmbedding\Ers6w\c
PS C:\Users\xxx\.julia\packages\DynamicallyLoadedEmbedding\Ers6w\c> gcc julia_embedding.c julia_cfunctions.c main.c -o embedding_example.exe
C:/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\xxx\AppData\Local\Temp\1\ccHvU39J.o:main.c:(.bss+0x0): multiple definition of `julia_sind'; C:\Users\xxx\AppData\Local\Temp\1\ccr9K1LG.o:julia_cfunctio:(.bss+0x0): first defined here
C:/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\xxx\AppData\Local\Temp\1\ccHvU39J.o:main.c:(.bss+0x8): multiple definition of `mutual_fibonacci'; C:\Users\xxx\AppData\Local\Temp\1\ccr9K1LG.o:julia_cfunctio:(.bss+0x8): first defined here
collect2.exe: error: ld returned 1 exit status
PS C:\Users\xxx\.julia\packages\DynamicallyLoadedEmbedding\Ers6w\c>

Thx

**Comment by GunnarFarneback** [comment]
At a first glance the compiler complaint doesn't seem unreasonable but I'm unclear on why it would work elsewhere if it's wrong. I'll look more into this when I get time.

**Comment by GunnarFarneback** [comment]
Fixed in #5.
